//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _IPC2_JDBR.WebServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://quetzalexpress.com", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://quetzalexpress.com", ConfigurationName="WebServiceRef.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://quetzalexpress.com/comprobar", ReplyAction="*")]
        _IPC2_JDBR.WebServiceRef.comprobarResponse comprobar(_IPC2_JDBR.WebServiceRef.comprobarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://quetzalexpress.com/comprobar", ReplyAction="*")]
        System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.comprobarResponse> comprobarAsync(_IPC2_JDBR.WebServiceRef.comprobarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento devuelveCategoriaResult del espacio de nombres http://quetzalexpress.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://quetzalexpress.com/devuelveCategoria", ReplyAction="*")]
        _IPC2_JDBR.WebServiceRef.devuelveCategoriaResponse devuelveCategoria(_IPC2_JDBR.WebServiceRef.devuelveCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://quetzalexpress.com/devuelveCategoria", ReplyAction="*")]
        System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.devuelveCategoriaResponse> devuelveCategoriaAsync(_IPC2_JDBR.WebServiceRef.devuelveCategoriaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cotizarResult del espacio de nombres http://quetzalexpress.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://quetzalexpress.com/cotizar", ReplyAction="*")]
        _IPC2_JDBR.WebServiceRef.cotizarResponse cotizar(_IPC2_JDBR.WebServiceRef.cotizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://quetzalexpress.com/cotizar", ReplyAction="*")]
        System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.cotizarResponse> cotizarAsync(_IPC2_JDBR.WebServiceRef.cotizarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento direccion del espacio de nombres http://quetzalexpress.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://quetzalexpress.com/cargarEmpleado", ReplyAction="*")]
        _IPC2_JDBR.WebServiceRef.cargarEmpleadoResponse cargarEmpleado(_IPC2_JDBR.WebServiceRef.cargarEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://quetzalexpress.com/cargarEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.cargarEmpleadoResponse> cargarEmpleadoAsync(_IPC2_JDBR.WebServiceRef.cargarEmpleadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento direccion del espacio de nombres http://quetzalexpress.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://quetzalexpress.com/cargarCategoria", ReplyAction="*")]
        _IPC2_JDBR.WebServiceRef.cargarCategoriaResponse cargarCategoria(_IPC2_JDBR.WebServiceRef.cargarCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://quetzalexpress.com/cargarCategoria", ReplyAction="*")]
        System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.cargarCategoriaResponse> cargarCategoriaAsync(_IPC2_JDBR.WebServiceRef.cargarCategoriaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CategoriasResult del espacio de nombres http://quetzalexpress.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://quetzalexpress.com/Categorias", ReplyAction="*")]
        _IPC2_JDBR.WebServiceRef.CategoriasResponse Categorias(_IPC2_JDBR.WebServiceRef.CategoriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://quetzalexpress.com/Categorias", ReplyAction="*")]
        System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.CategoriasResponse> CategoriasAsync(_IPC2_JDBR.WebServiceRef.CategoriasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento id del espacio de nombres http://quetzalexpress.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://quetzalexpress.com/despedir", ReplyAction="*")]
        _IPC2_JDBR.WebServiceRef.despedirResponse despedir(_IPC2_JDBR.WebServiceRef.despedirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://quetzalexpress.com/despedir", ReplyAction="*")]
        System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.despedirResponse> despedirAsync(_IPC2_JDBR.WebServiceRef.despedirRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://quetzalexpress.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://quetzalexpress.com/loginC", ReplyAction="*")]
        _IPC2_JDBR.WebServiceRef.loginCResponse loginC(_IPC2_JDBR.WebServiceRef.loginCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://quetzalexpress.com/loginC", ReplyAction="*")]
        System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.loginCResponse> loginCAsync(_IPC2_JDBR.WebServiceRef.loginCRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://quetzalexpress.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://quetzalexpress.com/loginE", ReplyAction="*")]
        _IPC2_JDBR.WebServiceRef.loginEResponse loginE(_IPC2_JDBR.WebServiceRef.loginERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://quetzalexpress.com/loginE", ReplyAction="*")]
        System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.loginEResponse> loginEAsync(_IPC2_JDBR.WebServiceRef.loginERequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comprobarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="comprobar", Namespace="http://quetzalexpress.com", Order=0)]
        public _IPC2_JDBR.WebServiceRef.comprobarRequestBody Body;
        
        public comprobarRequest() {
        }
        
        public comprobarRequest(_IPC2_JDBR.WebServiceRef.comprobarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://quetzalexpress.com")]
    public partial class comprobarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string error;
        
        public comprobarRequestBody() {
        }
        
        public comprobarRequestBody(string error) {
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class comprobarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="comprobarResponse", Namespace="http://quetzalexpress.com", Order=0)]
        public _IPC2_JDBR.WebServiceRef.comprobarResponseBody Body;
        
        public comprobarResponse() {
        }
        
        public comprobarResponse(_IPC2_JDBR.WebServiceRef.comprobarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://quetzalexpress.com")]
    public partial class comprobarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool comprobarResult;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string error;
        
        public comprobarResponseBody() {
        }
        
        public comprobarResponseBody(bool comprobarResult, string error) {
            this.comprobarResult = comprobarResult;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class devuelveCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="devuelveCategoria", Namespace="http://quetzalexpress.com", Order=0)]
        public _IPC2_JDBR.WebServiceRef.devuelveCategoriaRequestBody Body;
        
        public devuelveCategoriaRequest() {
        }
        
        public devuelveCategoriaRequest(_IPC2_JDBR.WebServiceRef.devuelveCategoriaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class devuelveCategoriaRequestBody {
        
        public devuelveCategoriaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class devuelveCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="devuelveCategoriaResponse", Namespace="http://quetzalexpress.com", Order=0)]
        public _IPC2_JDBR.WebServiceRef.devuelveCategoriaResponseBody Body;
        
        public devuelveCategoriaResponse() {
        }
        
        public devuelveCategoriaResponse(_IPC2_JDBR.WebServiceRef.devuelveCategoriaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://quetzalexpress.com")]
    public partial class devuelveCategoriaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _IPC2_JDBR.WebServiceRef.ArrayOfString devuelveCategoriaResult;
        
        public devuelveCategoriaResponseBody() {
        }
        
        public devuelveCategoriaResponseBody(_IPC2_JDBR.WebServiceRef.ArrayOfString devuelveCategoriaResult) {
            this.devuelveCategoriaResult = devuelveCategoriaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cotizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cotizar", Namespace="http://quetzalexpress.com", Order=0)]
        public _IPC2_JDBR.WebServiceRef.cotizarRequestBody Body;
        
        public cotizarRequest() {
        }
        
        public cotizarRequest(_IPC2_JDBR.WebServiceRef.cotizarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://quetzalexpress.com")]
    public partial class cotizarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float precio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float peso;
        
        public cotizarRequestBody() {
        }
        
        public cotizarRequestBody(float precio, float peso) {
            this.precio = precio;
            this.peso = peso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cotizarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cotizarResponse", Namespace="http://quetzalexpress.com", Order=0)]
        public _IPC2_JDBR.WebServiceRef.cotizarResponseBody Body;
        
        public cotizarResponse() {
        }
        
        public cotizarResponse(_IPC2_JDBR.WebServiceRef.cotizarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://quetzalexpress.com")]
    public partial class cotizarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cotizarResult;
        
        public cotizarResponseBody() {
        }
        
        public cotizarResponseBody(string cotizarResult) {
            this.cotizarResult = cotizarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargarEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cargarEmpleado", Namespace="http://quetzalexpress.com", Order=0)]
        public _IPC2_JDBR.WebServiceRef.cargarEmpleadoRequestBody Body;
        
        public cargarEmpleadoRequest() {
        }
        
        public cargarEmpleadoRequest(_IPC2_JDBR.WebServiceRef.cargarEmpleadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://quetzalexpress.com")]
    public partial class cargarEmpleadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string direccion;
        
        public cargarEmpleadoRequestBody() {
        }
        
        public cargarEmpleadoRequestBody(string direccion) {
            this.direccion = direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargarEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cargarEmpleadoResponse", Namespace="http://quetzalexpress.com", Order=0)]
        public _IPC2_JDBR.WebServiceRef.cargarEmpleadoResponseBody Body;
        
        public cargarEmpleadoResponse() {
        }
        
        public cargarEmpleadoResponse(_IPC2_JDBR.WebServiceRef.cargarEmpleadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class cargarEmpleadoResponseBody {
        
        public cargarEmpleadoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargarCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cargarCategoria", Namespace="http://quetzalexpress.com", Order=0)]
        public _IPC2_JDBR.WebServiceRef.cargarCategoriaRequestBody Body;
        
        public cargarCategoriaRequest() {
        }
        
        public cargarCategoriaRequest(_IPC2_JDBR.WebServiceRef.cargarCategoriaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://quetzalexpress.com")]
    public partial class cargarCategoriaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string direccion;
        
        public cargarCategoriaRequestBody() {
        }
        
        public cargarCategoriaRequestBody(string direccion) {
            this.direccion = direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargarCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cargarCategoriaResponse", Namespace="http://quetzalexpress.com", Order=0)]
        public _IPC2_JDBR.WebServiceRef.cargarCategoriaResponseBody Body;
        
        public cargarCategoriaResponse() {
        }
        
        public cargarCategoriaResponse(_IPC2_JDBR.WebServiceRef.cargarCategoriaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class cargarCategoriaResponseBody {
        
        public cargarCategoriaResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CategoriasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Categorias", Namespace="http://quetzalexpress.com", Order=0)]
        public _IPC2_JDBR.WebServiceRef.CategoriasRequestBody Body;
        
        public CategoriasRequest() {
        }
        
        public CategoriasRequest(_IPC2_JDBR.WebServiceRef.CategoriasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CategoriasRequestBody {
        
        public CategoriasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CategoriasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CategoriasResponse", Namespace="http://quetzalexpress.com", Order=0)]
        public _IPC2_JDBR.WebServiceRef.CategoriasResponseBody Body;
        
        public CategoriasResponse() {
        }
        
        public CategoriasResponse(_IPC2_JDBR.WebServiceRef.CategoriasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://quetzalexpress.com")]
    public partial class CategoriasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _IPC2_JDBR.WebServiceRef.ArrayOfString CategoriasResult;
        
        public CategoriasResponseBody() {
        }
        
        public CategoriasResponseBody(_IPC2_JDBR.WebServiceRef.ArrayOfString CategoriasResult) {
            this.CategoriasResult = CategoriasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class despedirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="despedir", Namespace="http://quetzalexpress.com", Order=0)]
        public _IPC2_JDBR.WebServiceRef.despedirRequestBody Body;
        
        public despedirRequest() {
        }
        
        public despedirRequest(_IPC2_JDBR.WebServiceRef.despedirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://quetzalexpress.com")]
    public partial class despedirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public despedirRequestBody() {
        }
        
        public despedirRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class despedirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="despedirResponse", Namespace="http://quetzalexpress.com", Order=0)]
        public _IPC2_JDBR.WebServiceRef.despedirResponseBody Body;
        
        public despedirResponse() {
        }
        
        public despedirResponse(_IPC2_JDBR.WebServiceRef.despedirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class despedirResponseBody {
        
        public despedirResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginC", Namespace="http://quetzalexpress.com", Order=0)]
        public _IPC2_JDBR.WebServiceRef.loginCRequestBody Body;
        
        public loginCRequest() {
        }
        
        public loginCRequest(_IPC2_JDBR.WebServiceRef.loginCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://quetzalexpress.com")]
    public partial class loginCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public loginCRequestBody() {
        }
        
        public loginCRequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginCResponse", Namespace="http://quetzalexpress.com", Order=0)]
        public _IPC2_JDBR.WebServiceRef.loginCResponseBody Body;
        
        public loginCResponse() {
        }
        
        public loginCResponse(_IPC2_JDBR.WebServiceRef.loginCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://quetzalexpress.com")]
    public partial class loginCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool loginCResult;
        
        public loginCResponseBody() {
        }
        
        public loginCResponseBody(bool loginCResult) {
            this.loginCResult = loginCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginE", Namespace="http://quetzalexpress.com", Order=0)]
        public _IPC2_JDBR.WebServiceRef.loginERequestBody Body;
        
        public loginERequest() {
        }
        
        public loginERequest(_IPC2_JDBR.WebServiceRef.loginERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://quetzalexpress.com")]
    public partial class loginERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public loginERequestBody() {
        }
        
        public loginERequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginEResponse", Namespace="http://quetzalexpress.com", Order=0)]
        public _IPC2_JDBR.WebServiceRef.loginEResponseBody Body;
        
        public loginEResponse() {
        }
        
        public loginEResponse(_IPC2_JDBR.WebServiceRef.loginEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://quetzalexpress.com")]
    public partial class loginEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int loginEResult;
        
        public loginEResponseBody() {
        }
        
        public loginEResponseBody(int loginEResult) {
            this.loginEResult = loginEResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : _IPC2_JDBR.WebServiceRef.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<_IPC2_JDBR.WebServiceRef.Service1Soap>, _IPC2_JDBR.WebServiceRef.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _IPC2_JDBR.WebServiceRef.comprobarResponse _IPC2_JDBR.WebServiceRef.Service1Soap.comprobar(_IPC2_JDBR.WebServiceRef.comprobarRequest request) {
            return base.Channel.comprobar(request);
        }
        
        public bool comprobar(ref string error) {
            _IPC2_JDBR.WebServiceRef.comprobarRequest inValue = new _IPC2_JDBR.WebServiceRef.comprobarRequest();
            inValue.Body = new _IPC2_JDBR.WebServiceRef.comprobarRequestBody();
            inValue.Body.error = error;
            _IPC2_JDBR.WebServiceRef.comprobarResponse retVal = ((_IPC2_JDBR.WebServiceRef.Service1Soap)(this)).comprobar(inValue);
            error = retVal.Body.error;
            return retVal.Body.comprobarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.comprobarResponse> _IPC2_JDBR.WebServiceRef.Service1Soap.comprobarAsync(_IPC2_JDBR.WebServiceRef.comprobarRequest request) {
            return base.Channel.comprobarAsync(request);
        }
        
        public System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.comprobarResponse> comprobarAsync(string error) {
            _IPC2_JDBR.WebServiceRef.comprobarRequest inValue = new _IPC2_JDBR.WebServiceRef.comprobarRequest();
            inValue.Body = new _IPC2_JDBR.WebServiceRef.comprobarRequestBody();
            inValue.Body.error = error;
            return ((_IPC2_JDBR.WebServiceRef.Service1Soap)(this)).comprobarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _IPC2_JDBR.WebServiceRef.devuelveCategoriaResponse _IPC2_JDBR.WebServiceRef.Service1Soap.devuelveCategoria(_IPC2_JDBR.WebServiceRef.devuelveCategoriaRequest request) {
            return base.Channel.devuelveCategoria(request);
        }
        
        public _IPC2_JDBR.WebServiceRef.ArrayOfString devuelveCategoria() {
            _IPC2_JDBR.WebServiceRef.devuelveCategoriaRequest inValue = new _IPC2_JDBR.WebServiceRef.devuelveCategoriaRequest();
            inValue.Body = new _IPC2_JDBR.WebServiceRef.devuelveCategoriaRequestBody();
            _IPC2_JDBR.WebServiceRef.devuelveCategoriaResponse retVal = ((_IPC2_JDBR.WebServiceRef.Service1Soap)(this)).devuelveCategoria(inValue);
            return retVal.Body.devuelveCategoriaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.devuelveCategoriaResponse> _IPC2_JDBR.WebServiceRef.Service1Soap.devuelveCategoriaAsync(_IPC2_JDBR.WebServiceRef.devuelveCategoriaRequest request) {
            return base.Channel.devuelveCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.devuelveCategoriaResponse> devuelveCategoriaAsync() {
            _IPC2_JDBR.WebServiceRef.devuelveCategoriaRequest inValue = new _IPC2_JDBR.WebServiceRef.devuelveCategoriaRequest();
            inValue.Body = new _IPC2_JDBR.WebServiceRef.devuelveCategoriaRequestBody();
            return ((_IPC2_JDBR.WebServiceRef.Service1Soap)(this)).devuelveCategoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _IPC2_JDBR.WebServiceRef.cotizarResponse _IPC2_JDBR.WebServiceRef.Service1Soap.cotizar(_IPC2_JDBR.WebServiceRef.cotizarRequest request) {
            return base.Channel.cotizar(request);
        }
        
        public string cotizar(float precio, float peso) {
            _IPC2_JDBR.WebServiceRef.cotizarRequest inValue = new _IPC2_JDBR.WebServiceRef.cotizarRequest();
            inValue.Body = new _IPC2_JDBR.WebServiceRef.cotizarRequestBody();
            inValue.Body.precio = precio;
            inValue.Body.peso = peso;
            _IPC2_JDBR.WebServiceRef.cotizarResponse retVal = ((_IPC2_JDBR.WebServiceRef.Service1Soap)(this)).cotizar(inValue);
            return retVal.Body.cotizarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.cotizarResponse> _IPC2_JDBR.WebServiceRef.Service1Soap.cotizarAsync(_IPC2_JDBR.WebServiceRef.cotizarRequest request) {
            return base.Channel.cotizarAsync(request);
        }
        
        public System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.cotizarResponse> cotizarAsync(float precio, float peso) {
            _IPC2_JDBR.WebServiceRef.cotizarRequest inValue = new _IPC2_JDBR.WebServiceRef.cotizarRequest();
            inValue.Body = new _IPC2_JDBR.WebServiceRef.cotizarRequestBody();
            inValue.Body.precio = precio;
            inValue.Body.peso = peso;
            return ((_IPC2_JDBR.WebServiceRef.Service1Soap)(this)).cotizarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _IPC2_JDBR.WebServiceRef.cargarEmpleadoResponse _IPC2_JDBR.WebServiceRef.Service1Soap.cargarEmpleado(_IPC2_JDBR.WebServiceRef.cargarEmpleadoRequest request) {
            return base.Channel.cargarEmpleado(request);
        }
        
        public void cargarEmpleado(string direccion) {
            _IPC2_JDBR.WebServiceRef.cargarEmpleadoRequest inValue = new _IPC2_JDBR.WebServiceRef.cargarEmpleadoRequest();
            inValue.Body = new _IPC2_JDBR.WebServiceRef.cargarEmpleadoRequestBody();
            inValue.Body.direccion = direccion;
            _IPC2_JDBR.WebServiceRef.cargarEmpleadoResponse retVal = ((_IPC2_JDBR.WebServiceRef.Service1Soap)(this)).cargarEmpleado(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.cargarEmpleadoResponse> _IPC2_JDBR.WebServiceRef.Service1Soap.cargarEmpleadoAsync(_IPC2_JDBR.WebServiceRef.cargarEmpleadoRequest request) {
            return base.Channel.cargarEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.cargarEmpleadoResponse> cargarEmpleadoAsync(string direccion) {
            _IPC2_JDBR.WebServiceRef.cargarEmpleadoRequest inValue = new _IPC2_JDBR.WebServiceRef.cargarEmpleadoRequest();
            inValue.Body = new _IPC2_JDBR.WebServiceRef.cargarEmpleadoRequestBody();
            inValue.Body.direccion = direccion;
            return ((_IPC2_JDBR.WebServiceRef.Service1Soap)(this)).cargarEmpleadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _IPC2_JDBR.WebServiceRef.cargarCategoriaResponse _IPC2_JDBR.WebServiceRef.Service1Soap.cargarCategoria(_IPC2_JDBR.WebServiceRef.cargarCategoriaRequest request) {
            return base.Channel.cargarCategoria(request);
        }
        
        public void cargarCategoria(string direccion) {
            _IPC2_JDBR.WebServiceRef.cargarCategoriaRequest inValue = new _IPC2_JDBR.WebServiceRef.cargarCategoriaRequest();
            inValue.Body = new _IPC2_JDBR.WebServiceRef.cargarCategoriaRequestBody();
            inValue.Body.direccion = direccion;
            _IPC2_JDBR.WebServiceRef.cargarCategoriaResponse retVal = ((_IPC2_JDBR.WebServiceRef.Service1Soap)(this)).cargarCategoria(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.cargarCategoriaResponse> _IPC2_JDBR.WebServiceRef.Service1Soap.cargarCategoriaAsync(_IPC2_JDBR.WebServiceRef.cargarCategoriaRequest request) {
            return base.Channel.cargarCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.cargarCategoriaResponse> cargarCategoriaAsync(string direccion) {
            _IPC2_JDBR.WebServiceRef.cargarCategoriaRequest inValue = new _IPC2_JDBR.WebServiceRef.cargarCategoriaRequest();
            inValue.Body = new _IPC2_JDBR.WebServiceRef.cargarCategoriaRequestBody();
            inValue.Body.direccion = direccion;
            return ((_IPC2_JDBR.WebServiceRef.Service1Soap)(this)).cargarCategoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _IPC2_JDBR.WebServiceRef.CategoriasResponse _IPC2_JDBR.WebServiceRef.Service1Soap.Categorias(_IPC2_JDBR.WebServiceRef.CategoriasRequest request) {
            return base.Channel.Categorias(request);
        }
        
        public _IPC2_JDBR.WebServiceRef.ArrayOfString Categorias() {
            _IPC2_JDBR.WebServiceRef.CategoriasRequest inValue = new _IPC2_JDBR.WebServiceRef.CategoriasRequest();
            inValue.Body = new _IPC2_JDBR.WebServiceRef.CategoriasRequestBody();
            _IPC2_JDBR.WebServiceRef.CategoriasResponse retVal = ((_IPC2_JDBR.WebServiceRef.Service1Soap)(this)).Categorias(inValue);
            return retVal.Body.CategoriasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.CategoriasResponse> _IPC2_JDBR.WebServiceRef.Service1Soap.CategoriasAsync(_IPC2_JDBR.WebServiceRef.CategoriasRequest request) {
            return base.Channel.CategoriasAsync(request);
        }
        
        public System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.CategoriasResponse> CategoriasAsync() {
            _IPC2_JDBR.WebServiceRef.CategoriasRequest inValue = new _IPC2_JDBR.WebServiceRef.CategoriasRequest();
            inValue.Body = new _IPC2_JDBR.WebServiceRef.CategoriasRequestBody();
            return ((_IPC2_JDBR.WebServiceRef.Service1Soap)(this)).CategoriasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _IPC2_JDBR.WebServiceRef.despedirResponse _IPC2_JDBR.WebServiceRef.Service1Soap.despedir(_IPC2_JDBR.WebServiceRef.despedirRequest request) {
            return base.Channel.despedir(request);
        }
        
        public void despedir(string id) {
            _IPC2_JDBR.WebServiceRef.despedirRequest inValue = new _IPC2_JDBR.WebServiceRef.despedirRequest();
            inValue.Body = new _IPC2_JDBR.WebServiceRef.despedirRequestBody();
            inValue.Body.id = id;
            _IPC2_JDBR.WebServiceRef.despedirResponse retVal = ((_IPC2_JDBR.WebServiceRef.Service1Soap)(this)).despedir(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.despedirResponse> _IPC2_JDBR.WebServiceRef.Service1Soap.despedirAsync(_IPC2_JDBR.WebServiceRef.despedirRequest request) {
            return base.Channel.despedirAsync(request);
        }
        
        public System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.despedirResponse> despedirAsync(string id) {
            _IPC2_JDBR.WebServiceRef.despedirRequest inValue = new _IPC2_JDBR.WebServiceRef.despedirRequest();
            inValue.Body = new _IPC2_JDBR.WebServiceRef.despedirRequestBody();
            inValue.Body.id = id;
            return ((_IPC2_JDBR.WebServiceRef.Service1Soap)(this)).despedirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _IPC2_JDBR.WebServiceRef.loginCResponse _IPC2_JDBR.WebServiceRef.Service1Soap.loginC(_IPC2_JDBR.WebServiceRef.loginCRequest request) {
            return base.Channel.loginC(request);
        }
        
        public bool loginC(string user, string pass) {
            _IPC2_JDBR.WebServiceRef.loginCRequest inValue = new _IPC2_JDBR.WebServiceRef.loginCRequest();
            inValue.Body = new _IPC2_JDBR.WebServiceRef.loginCRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            _IPC2_JDBR.WebServiceRef.loginCResponse retVal = ((_IPC2_JDBR.WebServiceRef.Service1Soap)(this)).loginC(inValue);
            return retVal.Body.loginCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.loginCResponse> _IPC2_JDBR.WebServiceRef.Service1Soap.loginCAsync(_IPC2_JDBR.WebServiceRef.loginCRequest request) {
            return base.Channel.loginCAsync(request);
        }
        
        public System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.loginCResponse> loginCAsync(string user, string pass) {
            _IPC2_JDBR.WebServiceRef.loginCRequest inValue = new _IPC2_JDBR.WebServiceRef.loginCRequest();
            inValue.Body = new _IPC2_JDBR.WebServiceRef.loginCRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((_IPC2_JDBR.WebServiceRef.Service1Soap)(this)).loginCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _IPC2_JDBR.WebServiceRef.loginEResponse _IPC2_JDBR.WebServiceRef.Service1Soap.loginE(_IPC2_JDBR.WebServiceRef.loginERequest request) {
            return base.Channel.loginE(request);
        }
        
        public int loginE(string user, string pass) {
            _IPC2_JDBR.WebServiceRef.loginERequest inValue = new _IPC2_JDBR.WebServiceRef.loginERequest();
            inValue.Body = new _IPC2_JDBR.WebServiceRef.loginERequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            _IPC2_JDBR.WebServiceRef.loginEResponse retVal = ((_IPC2_JDBR.WebServiceRef.Service1Soap)(this)).loginE(inValue);
            return retVal.Body.loginEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.loginEResponse> _IPC2_JDBR.WebServiceRef.Service1Soap.loginEAsync(_IPC2_JDBR.WebServiceRef.loginERequest request) {
            return base.Channel.loginEAsync(request);
        }
        
        public System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.loginEResponse> loginEAsync(string user, string pass) {
            _IPC2_JDBR.WebServiceRef.loginERequest inValue = new _IPC2_JDBR.WebServiceRef.loginERequest();
            inValue.Body = new _IPC2_JDBR.WebServiceRef.loginERequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((_IPC2_JDBR.WebServiceRef.Service1Soap)(this)).loginEAsync(inValue);
        }
    }
}
