//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _IPC2_JDBR.WebServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://quetzalexpress.com", ConfigurationName="WebServiceRef.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://quetzalexpress.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://quetzalexpress.com/HelloWorld", ReplyAction="*")]
        _IPC2_JDBR.WebServiceRef.HelloWorldResponse HelloWorld(_IPC2_JDBR.WebServiceRef.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://quetzalexpress.com/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.HelloWorldResponse> HelloWorldAsync(_IPC2_JDBR.WebServiceRef.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cotizarResult del espacio de nombres http://quetzalexpress.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://quetzalexpress.com/cotizar", ReplyAction="*")]
        _IPC2_JDBR.WebServiceRef.cotizarResponse cotizar(_IPC2_JDBR.WebServiceRef.cotizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://quetzalexpress.com/cotizar", ReplyAction="*")]
        System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.cotizarResponse> cotizarAsync(_IPC2_JDBR.WebServiceRef.cotizarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://quetzalexpress.com", Order=0)]
        public _IPC2_JDBR.WebServiceRef.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(_IPC2_JDBR.WebServiceRef.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://quetzalexpress.com", Order=0)]
        public _IPC2_JDBR.WebServiceRef.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(_IPC2_JDBR.WebServiceRef.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://quetzalexpress.com")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cotizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cotizar", Namespace="http://quetzalexpress.com", Order=0)]
        public _IPC2_JDBR.WebServiceRef.cotizarRequestBody Body;
        
        public cotizarRequest() {
        }
        
        public cotizarRequest(_IPC2_JDBR.WebServiceRef.cotizarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://quetzalexpress.com")]
    public partial class cotizarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float precio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float peso;
        
        public cotizarRequestBody() {
        }
        
        public cotizarRequestBody(float precio, float peso) {
            this.precio = precio;
            this.peso = peso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cotizarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cotizarResponse", Namespace="http://quetzalexpress.com", Order=0)]
        public _IPC2_JDBR.WebServiceRef.cotizarResponseBody Body;
        
        public cotizarResponse() {
        }
        
        public cotizarResponse(_IPC2_JDBR.WebServiceRef.cotizarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://quetzalexpress.com")]
    public partial class cotizarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cotizarResult;
        
        public cotizarResponseBody() {
        }
        
        public cotizarResponseBody(string cotizarResult) {
            this.cotizarResult = cotizarResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : _IPC2_JDBR.WebServiceRef.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<_IPC2_JDBR.WebServiceRef.Service1Soap>, _IPC2_JDBR.WebServiceRef.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _IPC2_JDBR.WebServiceRef.HelloWorldResponse _IPC2_JDBR.WebServiceRef.Service1Soap.HelloWorld(_IPC2_JDBR.WebServiceRef.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            _IPC2_JDBR.WebServiceRef.HelloWorldRequest inValue = new _IPC2_JDBR.WebServiceRef.HelloWorldRequest();
            inValue.Body = new _IPC2_JDBR.WebServiceRef.HelloWorldRequestBody();
            _IPC2_JDBR.WebServiceRef.HelloWorldResponse retVal = ((_IPC2_JDBR.WebServiceRef.Service1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.HelloWorldResponse> _IPC2_JDBR.WebServiceRef.Service1Soap.HelloWorldAsync(_IPC2_JDBR.WebServiceRef.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.HelloWorldResponse> HelloWorldAsync() {
            _IPC2_JDBR.WebServiceRef.HelloWorldRequest inValue = new _IPC2_JDBR.WebServiceRef.HelloWorldRequest();
            inValue.Body = new _IPC2_JDBR.WebServiceRef.HelloWorldRequestBody();
            return ((_IPC2_JDBR.WebServiceRef.Service1Soap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _IPC2_JDBR.WebServiceRef.cotizarResponse _IPC2_JDBR.WebServiceRef.Service1Soap.cotizar(_IPC2_JDBR.WebServiceRef.cotizarRequest request) {
            return base.Channel.cotizar(request);
        }
        
        public string cotizar(float precio, float peso) {
            _IPC2_JDBR.WebServiceRef.cotizarRequest inValue = new _IPC2_JDBR.WebServiceRef.cotizarRequest();
            inValue.Body = new _IPC2_JDBR.WebServiceRef.cotizarRequestBody();
            inValue.Body.precio = precio;
            inValue.Body.peso = peso;
            _IPC2_JDBR.WebServiceRef.cotizarResponse retVal = ((_IPC2_JDBR.WebServiceRef.Service1Soap)(this)).cotizar(inValue);
            return retVal.Body.cotizarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.cotizarResponse> _IPC2_JDBR.WebServiceRef.Service1Soap.cotizarAsync(_IPC2_JDBR.WebServiceRef.cotizarRequest request) {
            return base.Channel.cotizarAsync(request);
        }
        
        public System.Threading.Tasks.Task<_IPC2_JDBR.WebServiceRef.cotizarResponse> cotizarAsync(float precio, float peso) {
            _IPC2_JDBR.WebServiceRef.cotizarRequest inValue = new _IPC2_JDBR.WebServiceRef.cotizarRequest();
            inValue.Body = new _IPC2_JDBR.WebServiceRef.cotizarRequestBody();
            inValue.Body.precio = precio;
            inValue.Body.peso = peso;
            return ((_IPC2_JDBR.WebServiceRef.Service1Soap)(this)).cotizarAsync(inValue);
        }
    }
}
