//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _denissebr201224240_.websr {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="websr.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logC", ReplyAction="*")]
        _denissebr201224240_.websr.logCResponse logC(_denissebr201224240_.websr.logCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logC", ReplyAction="*")]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.logCResponse> logCAsync(_denissebr201224240_.websr.logCRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logE", ReplyAction="*")]
        _denissebr201224240_.websr.logEResponse logE(_denissebr201224240_.websr.logERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logE", ReplyAction="*")]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.logEResponse> logEAsync(_denissebr201224240_.websr.logERequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logD", ReplyAction="*")]
        _denissebr201224240_.websr.logDResponse logD(_denissebr201224240_.websr.logDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logD", ReplyAction="*")]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.logDResponse> logDAsync(_denissebr201224240_.websr.logDRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logA", ReplyAction="*")]
        _denissebr201224240_.websr.logAResponse logA(_denissebr201224240_.websr.logARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logA", ReplyAction="*")]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.logAResponse> logAAsync(_denissebr201224240_.websr.logARequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuarioC del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/usuario", ReplyAction="*")]
        _denissebr201224240_.websr.usuarioResponse usuario(_denissebr201224240_.websr.usuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/usuario", ReplyAction="*")]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.usuarioResponse> usuarioAsync(_denissebr201224240_.websr.usuarioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento asignarResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/asignar", ReplyAction="*")]
        _denissebr201224240_.websr.asignarResponse asignar(_denissebr201224240_.websr.asignarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/asignar", ReplyAction="*")]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.asignarResponse> asignarAsync(_denissebr201224240_.websr.asignarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento id del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/despedir", ReplyAction="*")]
        _denissebr201224240_.websr.despedirResponse despedir(_denissebr201224240_.websr.despedirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/despedir", ReplyAction="*")]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.despedirResponse> despedirAsync(_denissebr201224240_.websr.despedirRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento direccion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cargarEmpleado", ReplyAction="*")]
        _denissebr201224240_.websr.cargarEmpleadoResponse cargarEmpleado(_denissebr201224240_.websr.cargarEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cargarEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.cargarEmpleadoResponse> cargarEmpleadoAsync(_denissebr201224240_.websr.cargarEmpleadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento direccion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cargarCategoria", ReplyAction="*")]
        _denissebr201224240_.websr.cargarCategoriaResponse cargarCategoria(_denissebr201224240_.websr.cargarCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cargarCategoria", ReplyAction="*")]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.cargarCategoriaResponse> cargarCategoriaAsync(_denissebr201224240_.websr.cargarCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrar", ReplyAction="*")]
        void registrar();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrar", ReplyAction="*")]
        System.Threading.Tasks.Task registrarAsync();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cotizarResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cotizar", ReplyAction="*")]
        _denissebr201224240_.websr.cotizarResponse cotizar(_denissebr201224240_.websr.cotizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cotizar", ReplyAction="*")]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.cotizarResponse> cotizarAsync(_denissebr201224240_.websr.cotizarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CategoriasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Categorias", ReplyAction="*")]
        _denissebr201224240_.websr.CategoriasResponse Categorias(_denissebr201224240_.websr.CategoriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Categorias", ReplyAction="*")]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.CategoriasResponse> CategoriasAsync(_denissebr201224240_.websr.CategoriasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logC", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.logCRequestBody Body;
        
        public logCRequest() {
        }
        
        public logCRequest(_denissebr201224240_.websr.logCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public logCRequestBody() {
        }
        
        public logCRequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logCResponse", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.logCResponseBody Body;
        
        public logCResponse() {
        }
        
        public logCResponse(_denissebr201224240_.websr.logCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool logCResult;
        
        public logCResponseBody() {
        }
        
        public logCResponseBody(bool logCResult) {
            this.logCResult = logCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logE", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.logERequestBody Body;
        
        public logERequest() {
        }
        
        public logERequest(_denissebr201224240_.websr.logERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public logERequestBody() {
        }
        
        public logERequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logEResponse", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.logEResponseBody Body;
        
        public logEResponse() {
        }
        
        public logEResponse(_denissebr201224240_.websr.logEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool logEResult;
        
        public logEResponseBody() {
        }
        
        public logEResponseBody(bool logEResult) {
            this.logEResult = logEResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logD", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.logDRequestBody Body;
        
        public logDRequest() {
        }
        
        public logDRequest(_denissebr201224240_.websr.logDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public logDRequestBody() {
        }
        
        public logDRequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logDResponse", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.logDResponseBody Body;
        
        public logDResponse() {
        }
        
        public logDResponse(_denissebr201224240_.websr.logDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool logDResult;
        
        public logDResponseBody() {
        }
        
        public logDResponseBody(bool logDResult) {
            this.logDResult = logDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logA", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.logARequestBody Body;
        
        public logARequest() {
        }
        
        public logARequest(_denissebr201224240_.websr.logARequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logARequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public logARequestBody() {
        }
        
        public logARequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logAResponse", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.logAResponseBody Body;
        
        public logAResponse() {
        }
        
        public logAResponse(_denissebr201224240_.websr.logAResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logAResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool logAResult;
        
        public logAResponseBody() {
        }
        
        public logAResponseBody(bool logAResult) {
            this.logAResult = logAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class usuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="usuario", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.usuarioRequestBody Body;
        
        public usuarioRequest() {
        }
        
        public usuarioRequest(_denissebr201224240_.websr.usuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class usuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuarioC;
        
        public usuarioRequestBody() {
        }
        
        public usuarioRequestBody(string usuarioC) {
            this.usuarioC = usuarioC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class usuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="usuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.usuarioResponseBody Body;
        
        public usuarioResponse() {
        }
        
        public usuarioResponse(_denissebr201224240_.websr.usuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class usuarioResponseBody {
        
        public usuarioResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class asignarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="asignar", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.asignarRequestBody Body;
        
        public asignarRequest() {
        }
        
        public asignarRequest(_denissebr201224240_.websr.asignarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class asignarRequestBody {
        
        public asignarRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class asignarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="asignarResponse", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.asignarResponseBody Body;
        
        public asignarResponse() {
        }
        
        public asignarResponse(_denissebr201224240_.websr.asignarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class asignarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string asignarResult;
        
        public asignarResponseBody() {
        }
        
        public asignarResponseBody(string asignarResult) {
            this.asignarResult = asignarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class despedirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="despedir", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.despedirRequestBody Body;
        
        public despedirRequest() {
        }
        
        public despedirRequest(_denissebr201224240_.websr.despedirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class despedirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public despedirRequestBody() {
        }
        
        public despedirRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class despedirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="despedirResponse", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.despedirResponseBody Body;
        
        public despedirResponse() {
        }
        
        public despedirResponse(_denissebr201224240_.websr.despedirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class despedirResponseBody {
        
        public despedirResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargarEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cargarEmpleado", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.cargarEmpleadoRequestBody Body;
        
        public cargarEmpleadoRequest() {
        }
        
        public cargarEmpleadoRequest(_denissebr201224240_.websr.cargarEmpleadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class cargarEmpleadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string direccion;
        
        public cargarEmpleadoRequestBody() {
        }
        
        public cargarEmpleadoRequestBody(string direccion) {
            this.direccion = direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargarEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cargarEmpleadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.cargarEmpleadoResponseBody Body;
        
        public cargarEmpleadoResponse() {
        }
        
        public cargarEmpleadoResponse(_denissebr201224240_.websr.cargarEmpleadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class cargarEmpleadoResponseBody {
        
        public cargarEmpleadoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargarCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cargarCategoria", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.cargarCategoriaRequestBody Body;
        
        public cargarCategoriaRequest() {
        }
        
        public cargarCategoriaRequest(_denissebr201224240_.websr.cargarCategoriaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class cargarCategoriaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string direccion;
        
        public cargarCategoriaRequestBody() {
        }
        
        public cargarCategoriaRequestBody(string direccion) {
            this.direccion = direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargarCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cargarCategoriaResponse", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.cargarCategoriaResponseBody Body;
        
        public cargarCategoriaResponse() {
        }
        
        public cargarCategoriaResponse(_denissebr201224240_.websr.cargarCategoriaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class cargarCategoriaResponseBody {
        
        public cargarCategoriaResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cotizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cotizar", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.cotizarRequestBody Body;
        
        public cotizarRequest() {
        }
        
        public cotizarRequest(_denissebr201224240_.websr.cotizarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class cotizarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float precio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float peso;
        
        public cotizarRequestBody() {
        }
        
        public cotizarRequestBody(float precio, float peso) {
            this.precio = precio;
            this.peso = peso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cotizarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cotizarResponse", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.cotizarResponseBody Body;
        
        public cotizarResponse() {
        }
        
        public cotizarResponse(_denissebr201224240_.websr.cotizarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class cotizarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cotizarResult;
        
        public cotizarResponseBody() {
        }
        
        public cotizarResponseBody(string cotizarResult) {
            this.cotizarResult = cotizarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CategoriasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Categorias", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.CategoriasRequestBody Body;
        
        public CategoriasRequest() {
        }
        
        public CategoriasRequest(_denissebr201224240_.websr.CategoriasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CategoriasRequestBody {
        
        public CategoriasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CategoriasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CategoriasResponse", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.CategoriasResponseBody Body;
        
        public CategoriasResponse() {
        }
        
        public CategoriasResponse(_denissebr201224240_.websr.CategoriasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CategoriasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _denissebr201224240_.websr.ArrayOfString CategoriasResult;
        
        public CategoriasResponseBody() {
        }
        
        public CategoriasResponseBody(_denissebr201224240_.websr.ArrayOfString CategoriasResult) {
            this.CategoriasResult = CategoriasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : _denissebr201224240_.websr.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<_denissebr201224240_.websr.Service1Soap>, _denissebr201224240_.websr.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _denissebr201224240_.websr.logCResponse _denissebr201224240_.websr.Service1Soap.logC(_denissebr201224240_.websr.logCRequest request) {
            return base.Channel.logC(request);
        }
        
        public bool logC(string user, string pass) {
            _denissebr201224240_.websr.logCRequest inValue = new _denissebr201224240_.websr.logCRequest();
            inValue.Body = new _denissebr201224240_.websr.logCRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            _denissebr201224240_.websr.logCResponse retVal = ((_denissebr201224240_.websr.Service1Soap)(this)).logC(inValue);
            return retVal.Body.logCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.logCResponse> _denissebr201224240_.websr.Service1Soap.logCAsync(_denissebr201224240_.websr.logCRequest request) {
            return base.Channel.logCAsync(request);
        }
        
        public System.Threading.Tasks.Task<_denissebr201224240_.websr.logCResponse> logCAsync(string user, string pass) {
            _denissebr201224240_.websr.logCRequest inValue = new _denissebr201224240_.websr.logCRequest();
            inValue.Body = new _denissebr201224240_.websr.logCRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((_denissebr201224240_.websr.Service1Soap)(this)).logCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _denissebr201224240_.websr.logEResponse _denissebr201224240_.websr.Service1Soap.logE(_denissebr201224240_.websr.logERequest request) {
            return base.Channel.logE(request);
        }
        
        public bool logE(string user, string pass) {
            _denissebr201224240_.websr.logERequest inValue = new _denissebr201224240_.websr.logERequest();
            inValue.Body = new _denissebr201224240_.websr.logERequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            _denissebr201224240_.websr.logEResponse retVal = ((_denissebr201224240_.websr.Service1Soap)(this)).logE(inValue);
            return retVal.Body.logEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.logEResponse> _denissebr201224240_.websr.Service1Soap.logEAsync(_denissebr201224240_.websr.logERequest request) {
            return base.Channel.logEAsync(request);
        }
        
        public System.Threading.Tasks.Task<_denissebr201224240_.websr.logEResponse> logEAsync(string user, string pass) {
            _denissebr201224240_.websr.logERequest inValue = new _denissebr201224240_.websr.logERequest();
            inValue.Body = new _denissebr201224240_.websr.logERequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((_denissebr201224240_.websr.Service1Soap)(this)).logEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _denissebr201224240_.websr.logDResponse _denissebr201224240_.websr.Service1Soap.logD(_denissebr201224240_.websr.logDRequest request) {
            return base.Channel.logD(request);
        }
        
        public bool logD(string user, string pass) {
            _denissebr201224240_.websr.logDRequest inValue = new _denissebr201224240_.websr.logDRequest();
            inValue.Body = new _denissebr201224240_.websr.logDRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            _denissebr201224240_.websr.logDResponse retVal = ((_denissebr201224240_.websr.Service1Soap)(this)).logD(inValue);
            return retVal.Body.logDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.logDResponse> _denissebr201224240_.websr.Service1Soap.logDAsync(_denissebr201224240_.websr.logDRequest request) {
            return base.Channel.logDAsync(request);
        }
        
        public System.Threading.Tasks.Task<_denissebr201224240_.websr.logDResponse> logDAsync(string user, string pass) {
            _denissebr201224240_.websr.logDRequest inValue = new _denissebr201224240_.websr.logDRequest();
            inValue.Body = new _denissebr201224240_.websr.logDRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((_denissebr201224240_.websr.Service1Soap)(this)).logDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _denissebr201224240_.websr.logAResponse _denissebr201224240_.websr.Service1Soap.logA(_denissebr201224240_.websr.logARequest request) {
            return base.Channel.logA(request);
        }
        
        public bool logA(string user, string pass) {
            _denissebr201224240_.websr.logARequest inValue = new _denissebr201224240_.websr.logARequest();
            inValue.Body = new _denissebr201224240_.websr.logARequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            _denissebr201224240_.websr.logAResponse retVal = ((_denissebr201224240_.websr.Service1Soap)(this)).logA(inValue);
            return retVal.Body.logAResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.logAResponse> _denissebr201224240_.websr.Service1Soap.logAAsync(_denissebr201224240_.websr.logARequest request) {
            return base.Channel.logAAsync(request);
        }
        
        public System.Threading.Tasks.Task<_denissebr201224240_.websr.logAResponse> logAAsync(string user, string pass) {
            _denissebr201224240_.websr.logARequest inValue = new _denissebr201224240_.websr.logARequest();
            inValue.Body = new _denissebr201224240_.websr.logARequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((_denissebr201224240_.websr.Service1Soap)(this)).logAAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _denissebr201224240_.websr.usuarioResponse _denissebr201224240_.websr.Service1Soap.usuario(_denissebr201224240_.websr.usuarioRequest request) {
            return base.Channel.usuario(request);
        }
        
        public void usuario(string usuarioC) {
            _denissebr201224240_.websr.usuarioRequest inValue = new _denissebr201224240_.websr.usuarioRequest();
            inValue.Body = new _denissebr201224240_.websr.usuarioRequestBody();
            inValue.Body.usuarioC = usuarioC;
            _denissebr201224240_.websr.usuarioResponse retVal = ((_denissebr201224240_.websr.Service1Soap)(this)).usuario(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.usuarioResponse> _denissebr201224240_.websr.Service1Soap.usuarioAsync(_denissebr201224240_.websr.usuarioRequest request) {
            return base.Channel.usuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<_denissebr201224240_.websr.usuarioResponse> usuarioAsync(string usuarioC) {
            _denissebr201224240_.websr.usuarioRequest inValue = new _denissebr201224240_.websr.usuarioRequest();
            inValue.Body = new _denissebr201224240_.websr.usuarioRequestBody();
            inValue.Body.usuarioC = usuarioC;
            return ((_denissebr201224240_.websr.Service1Soap)(this)).usuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _denissebr201224240_.websr.asignarResponse _denissebr201224240_.websr.Service1Soap.asignar(_denissebr201224240_.websr.asignarRequest request) {
            return base.Channel.asignar(request);
        }
        
        public string asignar() {
            _denissebr201224240_.websr.asignarRequest inValue = new _denissebr201224240_.websr.asignarRequest();
            inValue.Body = new _denissebr201224240_.websr.asignarRequestBody();
            _denissebr201224240_.websr.asignarResponse retVal = ((_denissebr201224240_.websr.Service1Soap)(this)).asignar(inValue);
            return retVal.Body.asignarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.asignarResponse> _denissebr201224240_.websr.Service1Soap.asignarAsync(_denissebr201224240_.websr.asignarRequest request) {
            return base.Channel.asignarAsync(request);
        }
        
        public System.Threading.Tasks.Task<_denissebr201224240_.websr.asignarResponse> asignarAsync() {
            _denissebr201224240_.websr.asignarRequest inValue = new _denissebr201224240_.websr.asignarRequest();
            inValue.Body = new _denissebr201224240_.websr.asignarRequestBody();
            return ((_denissebr201224240_.websr.Service1Soap)(this)).asignarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _denissebr201224240_.websr.despedirResponse _denissebr201224240_.websr.Service1Soap.despedir(_denissebr201224240_.websr.despedirRequest request) {
            return base.Channel.despedir(request);
        }
        
        public void despedir(string id) {
            _denissebr201224240_.websr.despedirRequest inValue = new _denissebr201224240_.websr.despedirRequest();
            inValue.Body = new _denissebr201224240_.websr.despedirRequestBody();
            inValue.Body.id = id;
            _denissebr201224240_.websr.despedirResponse retVal = ((_denissebr201224240_.websr.Service1Soap)(this)).despedir(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.despedirResponse> _denissebr201224240_.websr.Service1Soap.despedirAsync(_denissebr201224240_.websr.despedirRequest request) {
            return base.Channel.despedirAsync(request);
        }
        
        public System.Threading.Tasks.Task<_denissebr201224240_.websr.despedirResponse> despedirAsync(string id) {
            _denissebr201224240_.websr.despedirRequest inValue = new _denissebr201224240_.websr.despedirRequest();
            inValue.Body = new _denissebr201224240_.websr.despedirRequestBody();
            inValue.Body.id = id;
            return ((_denissebr201224240_.websr.Service1Soap)(this)).despedirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _denissebr201224240_.websr.cargarEmpleadoResponse _denissebr201224240_.websr.Service1Soap.cargarEmpleado(_denissebr201224240_.websr.cargarEmpleadoRequest request) {
            return base.Channel.cargarEmpleado(request);
        }
        
        public void cargarEmpleado(string direccion) {
            _denissebr201224240_.websr.cargarEmpleadoRequest inValue = new _denissebr201224240_.websr.cargarEmpleadoRequest();
            inValue.Body = new _denissebr201224240_.websr.cargarEmpleadoRequestBody();
            inValue.Body.direccion = direccion;
            _denissebr201224240_.websr.cargarEmpleadoResponse retVal = ((_denissebr201224240_.websr.Service1Soap)(this)).cargarEmpleado(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.cargarEmpleadoResponse> _denissebr201224240_.websr.Service1Soap.cargarEmpleadoAsync(_denissebr201224240_.websr.cargarEmpleadoRequest request) {
            return base.Channel.cargarEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<_denissebr201224240_.websr.cargarEmpleadoResponse> cargarEmpleadoAsync(string direccion) {
            _denissebr201224240_.websr.cargarEmpleadoRequest inValue = new _denissebr201224240_.websr.cargarEmpleadoRequest();
            inValue.Body = new _denissebr201224240_.websr.cargarEmpleadoRequestBody();
            inValue.Body.direccion = direccion;
            return ((_denissebr201224240_.websr.Service1Soap)(this)).cargarEmpleadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _denissebr201224240_.websr.cargarCategoriaResponse _denissebr201224240_.websr.Service1Soap.cargarCategoria(_denissebr201224240_.websr.cargarCategoriaRequest request) {
            return base.Channel.cargarCategoria(request);
        }
        
        public void cargarCategoria(string direccion) {
            _denissebr201224240_.websr.cargarCategoriaRequest inValue = new _denissebr201224240_.websr.cargarCategoriaRequest();
            inValue.Body = new _denissebr201224240_.websr.cargarCategoriaRequestBody();
            inValue.Body.direccion = direccion;
            _denissebr201224240_.websr.cargarCategoriaResponse retVal = ((_denissebr201224240_.websr.Service1Soap)(this)).cargarCategoria(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.cargarCategoriaResponse> _denissebr201224240_.websr.Service1Soap.cargarCategoriaAsync(_denissebr201224240_.websr.cargarCategoriaRequest request) {
            return base.Channel.cargarCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<_denissebr201224240_.websr.cargarCategoriaResponse> cargarCategoriaAsync(string direccion) {
            _denissebr201224240_.websr.cargarCategoriaRequest inValue = new _denissebr201224240_.websr.cargarCategoriaRequest();
            inValue.Body = new _denissebr201224240_.websr.cargarCategoriaRequestBody();
            inValue.Body.direccion = direccion;
            return ((_denissebr201224240_.websr.Service1Soap)(this)).cargarCategoriaAsync(inValue);
        }
        
        public void registrar() {
            base.Channel.registrar();
        }
        
        public System.Threading.Tasks.Task registrarAsync() {
            return base.Channel.registrarAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _denissebr201224240_.websr.cotizarResponse _denissebr201224240_.websr.Service1Soap.cotizar(_denissebr201224240_.websr.cotizarRequest request) {
            return base.Channel.cotizar(request);
        }
        
        public string cotizar(float precio, float peso) {
            _denissebr201224240_.websr.cotizarRequest inValue = new _denissebr201224240_.websr.cotizarRequest();
            inValue.Body = new _denissebr201224240_.websr.cotizarRequestBody();
            inValue.Body.precio = precio;
            inValue.Body.peso = peso;
            _denissebr201224240_.websr.cotizarResponse retVal = ((_denissebr201224240_.websr.Service1Soap)(this)).cotizar(inValue);
            return retVal.Body.cotizarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.cotizarResponse> _denissebr201224240_.websr.Service1Soap.cotizarAsync(_denissebr201224240_.websr.cotizarRequest request) {
            return base.Channel.cotizarAsync(request);
        }
        
        public System.Threading.Tasks.Task<_denissebr201224240_.websr.cotizarResponse> cotizarAsync(float precio, float peso) {
            _denissebr201224240_.websr.cotizarRequest inValue = new _denissebr201224240_.websr.cotizarRequest();
            inValue.Body = new _denissebr201224240_.websr.cotizarRequestBody();
            inValue.Body.precio = precio;
            inValue.Body.peso = peso;
            return ((_denissebr201224240_.websr.Service1Soap)(this)).cotizarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _denissebr201224240_.websr.CategoriasResponse _denissebr201224240_.websr.Service1Soap.Categorias(_denissebr201224240_.websr.CategoriasRequest request) {
            return base.Channel.Categorias(request);
        }
        
        public _denissebr201224240_.websr.ArrayOfString Categorias() {
            _denissebr201224240_.websr.CategoriasRequest inValue = new _denissebr201224240_.websr.CategoriasRequest();
            inValue.Body = new _denissebr201224240_.websr.CategoriasRequestBody();
            _denissebr201224240_.websr.CategoriasResponse retVal = ((_denissebr201224240_.websr.Service1Soap)(this)).Categorias(inValue);
            return retVal.Body.CategoriasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.CategoriasResponse> _denissebr201224240_.websr.Service1Soap.CategoriasAsync(_denissebr201224240_.websr.CategoriasRequest request) {
            return base.Channel.CategoriasAsync(request);
        }
        
        public System.Threading.Tasks.Task<_denissebr201224240_.websr.CategoriasResponse> CategoriasAsync() {
            _denissebr201224240_.websr.CategoriasRequest inValue = new _denissebr201224240_.websr.CategoriasRequest();
            inValue.Body = new _denissebr201224240_.websr.CategoriasRequestBody();
            return ((_denissebr201224240_.websr.Service1Soap)(this)).CategoriasAsync(inValue);
        }
    }
}
