//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _denissebr201224240_.websr {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="websr.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logC", ReplyAction="*")]
        _denissebr201224240_.websr.logCResponse logC(_denissebr201224240_.websr.logCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logC", ReplyAction="*")]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.logCResponse> logCAsync(_denissebr201224240_.websr.logCRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logE", ReplyAction="*")]
        _denissebr201224240_.websr.logEResponse logE(_denissebr201224240_.websr.logERequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logE", ReplyAction="*")]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.logEResponse> logEAsync(_denissebr201224240_.websr.logERequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logD", ReplyAction="*")]
        _denissebr201224240_.websr.logDResponse logD(_denissebr201224240_.websr.logDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logD", ReplyAction="*")]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.logDResponse> logDAsync(_denissebr201224240_.websr.logDRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logA", ReplyAction="*")]
        _denissebr201224240_.websr.logAResponse logA(_denissebr201224240_.websr.logARequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logA", ReplyAction="*")]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.logAResponse> logAAsync(_denissebr201224240_.websr.logARequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento id del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/despedir", ReplyAction="*")]
        _denissebr201224240_.websr.despedirResponse despedir(_denissebr201224240_.websr.despedirRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/despedir", ReplyAction="*")]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.despedirResponse> despedirAsync(_denissebr201224240_.websr.despedirRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento direccion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cargarEmpleado", ReplyAction="*")]
        _denissebr201224240_.websr.cargarEmpleadoResponse cargarEmpleado(_denissebr201224240_.websr.cargarEmpleadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cargarEmpleado", ReplyAction="*")]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.cargarEmpleadoResponse> cargarEmpleadoAsync(_denissebr201224240_.websr.cargarEmpleadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento direccion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cargarCategoria", ReplyAction="*")]
        _denissebr201224240_.websr.cargarCategoriaResponse cargarCategoria(_denissebr201224240_.websr.cargarCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cargarCategoria", ReplyAction="*")]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.cargarCategoriaResponse> cargarCategoriaAsync(_denissebr201224240_.websr.cargarCategoriaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sucursalResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sucursal", ReplyAction="*")]
        _denissebr201224240_.websr.sucursalResponse sucursal(_denissebr201224240_.websr.sucursalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sucursal", ReplyAction="*")]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.sucursalResponse> sucursalAsync(_denissebr201224240_.websr.sucursalRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrar", ReplyAction="*")]
        _denissebr201224240_.websr.registrarResponse registrar(_denissebr201224240_.websr.registrarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/registrar", ReplyAction="*")]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.registrarResponse> registrarAsync(_denissebr201224240_.websr.registrarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento cotizarResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cotizar", ReplyAction="*")]
        _denissebr201224240_.websr.cotizarResponse cotizar(_denissebr201224240_.websr.cotizarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/cotizar", ReplyAction="*")]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.cotizarResponse> cotizarAsync(_denissebr201224240_.websr.cotizarRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento CategoriasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Categorias", ReplyAction="*")]
        _denissebr201224240_.websr.CategoriasResponse Categorias(_denissebr201224240_.websr.CategoriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Categorias", ReplyAction="*")]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.CategoriasResponse> CategoriasAsync(_denissebr201224240_.websr.CategoriasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverNombreCliente", ReplyAction="*")]
        _denissebr201224240_.websr.DevolverNombreClienteResponse DevolverNombreCliente(_denissebr201224240_.websr.DevolverNombreClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevolverNombreCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.DevolverNombreClienteResponse> DevolverNombreClienteAsync(_denissebr201224240_.websr.DevolverNombreClienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logC", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.logCRequestBody Body;
        
        public logCRequest() {
        }
        
        public logCRequest(_denissebr201224240_.websr.logCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public logCRequestBody() {
        }
        
        public logCRequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logCResponse", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.logCResponseBody Body;
        
        public logCResponse() {
        }
        
        public logCResponse(_denissebr201224240_.websr.logCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool logCResult;
        
        public logCResponseBody() {
        }
        
        public logCResponseBody(bool logCResult) {
            this.logCResult = logCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logERequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logE", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.logERequestBody Body;
        
        public logERequest() {
        }
        
        public logERequest(_denissebr201224240_.websr.logERequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logERequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public logERequestBody() {
        }
        
        public logERequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logEResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logEResponse", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.logEResponseBody Body;
        
        public logEResponse() {
        }
        
        public logEResponse(_denissebr201224240_.websr.logEResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logEResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool logEResult;
        
        public logEResponseBody() {
        }
        
        public logEResponseBody(bool logEResult) {
            this.logEResult = logEResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logD", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.logDRequestBody Body;
        
        public logDRequest() {
        }
        
        public logDRequest(_denissebr201224240_.websr.logDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public logDRequestBody() {
        }
        
        public logDRequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logDResponse", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.logDResponseBody Body;
        
        public logDResponse() {
        }
        
        public logDResponse(_denissebr201224240_.websr.logDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool logDResult;
        
        public logDResponseBody() {
        }
        
        public logDResponseBody(bool logDResult) {
            this.logDResult = logDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logA", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.logARequestBody Body;
        
        public logARequest() {
        }
        
        public logARequest(_denissebr201224240_.websr.logARequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logARequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public logARequestBody() {
        }
        
        public logARequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logAResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logAResponse", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.logAResponseBody Body;
        
        public logAResponse() {
        }
        
        public logAResponse(_denissebr201224240_.websr.logAResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logAResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool logAResult;
        
        public logAResponseBody() {
        }
        
        public logAResponseBody(bool logAResult) {
            this.logAResult = logAResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class despedirRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="despedir", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.despedirRequestBody Body;
        
        public despedirRequest() {
        }
        
        public despedirRequest(_denissebr201224240_.websr.despedirRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class despedirRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public despedirRequestBody() {
        }
        
        public despedirRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class despedirResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="despedirResponse", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.despedirResponseBody Body;
        
        public despedirResponse() {
        }
        
        public despedirResponse(_denissebr201224240_.websr.despedirResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class despedirResponseBody {
        
        public despedirResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargarEmpleadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cargarEmpleado", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.cargarEmpleadoRequestBody Body;
        
        public cargarEmpleadoRequest() {
        }
        
        public cargarEmpleadoRequest(_denissebr201224240_.websr.cargarEmpleadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class cargarEmpleadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string direccion;
        
        public cargarEmpleadoRequestBody() {
        }
        
        public cargarEmpleadoRequestBody(string direccion) {
            this.direccion = direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargarEmpleadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cargarEmpleadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.cargarEmpleadoResponseBody Body;
        
        public cargarEmpleadoResponse() {
        }
        
        public cargarEmpleadoResponse(_denissebr201224240_.websr.cargarEmpleadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class cargarEmpleadoResponseBody {
        
        public cargarEmpleadoResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargarCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cargarCategoria", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.cargarCategoriaRequestBody Body;
        
        public cargarCategoriaRequest() {
        }
        
        public cargarCategoriaRequest(_denissebr201224240_.websr.cargarCategoriaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class cargarCategoriaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string direccion;
        
        public cargarCategoriaRequestBody() {
        }
        
        public cargarCategoriaRequestBody(string direccion) {
            this.direccion = direccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargarCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cargarCategoriaResponse", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.cargarCategoriaResponseBody Body;
        
        public cargarCategoriaResponse() {
        }
        
        public cargarCategoriaResponse(_denissebr201224240_.websr.cargarCategoriaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class cargarCategoriaResponseBody {
        
        public cargarCategoriaResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sucursalRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sucursal", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.sucursalRequestBody Body;
        
        public sucursalRequest() {
        }
        
        public sucursalRequest(_denissebr201224240_.websr.sucursalRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class sucursalRequestBody {
        
        public sucursalRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sucursalResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sucursalResponse", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.sucursalResponseBody Body;
        
        public sucursalResponse() {
        }
        
        public sucursalResponse(_denissebr201224240_.websr.sucursalResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sucursalResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _denissebr201224240_.websr.ArrayOfString sucursalResult;
        
        public sucursalResponseBody() {
        }
        
        public sucursalResponseBody(_denissebr201224240_.websr.ArrayOfString sucursalResult) {
            this.sucursalResult = sucursalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrar", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.registrarRequestBody Body;
        
        public registrarRequest() {
        }
        
        public registrarRequest(_denissebr201224240_.websr.registrarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class registrarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int dpi;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int nit;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string direccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public long tarjeta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int sucursal;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string contra;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int estado;
        
        public registrarRequestBody() {
        }
        
        public registrarRequestBody(int dpi, string nombre, string apellido, int nit, int telefono, string direccion, long tarjeta, int sucursal, string usuario, string contra, int estado) {
            this.dpi = dpi;
            this.nombre = nombre;
            this.apellido = apellido;
            this.nit = nit;
            this.telefono = telefono;
            this.direccion = direccion;
            this.tarjeta = tarjeta;
            this.sucursal = sucursal;
            this.usuario = usuario;
            this.contra = contra;
            this.estado = estado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class registrarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="registrarResponse", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.registrarResponseBody Body;
        
        public registrarResponse() {
        }
        
        public registrarResponse(_denissebr201224240_.websr.registrarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class registrarResponseBody {
        
        public registrarResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cotizarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cotizar", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.cotizarRequestBody Body;
        
        public cotizarRequest() {
        }
        
        public cotizarRequest(_denissebr201224240_.websr.cotizarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class cotizarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public float precio;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public float peso;
        
        public cotizarRequestBody() {
        }
        
        public cotizarRequestBody(float precio, float peso) {
            this.precio = precio;
            this.peso = peso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cotizarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="cotizarResponse", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.cotizarResponseBody Body;
        
        public cotizarResponse() {
        }
        
        public cotizarResponse(_denissebr201224240_.websr.cotizarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class cotizarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cotizarResult;
        
        public cotizarResponseBody() {
        }
        
        public cotizarResponseBody(string cotizarResult) {
            this.cotizarResult = cotizarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CategoriasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Categorias", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.CategoriasRequestBody Body;
        
        public CategoriasRequest() {
        }
        
        public CategoriasRequest(_denissebr201224240_.websr.CategoriasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class CategoriasRequestBody {
        
        public CategoriasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CategoriasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CategoriasResponse", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.CategoriasResponseBody Body;
        
        public CategoriasResponse() {
        }
        
        public CategoriasResponse(_denissebr201224240_.websr.CategoriasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CategoriasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public _denissebr201224240_.websr.ArrayOfString CategoriasResult;
        
        public CategoriasResponseBody() {
        }
        
        public CategoriasResponseBody(_denissebr201224240_.websr.ArrayOfString CategoriasResult) {
            this.CategoriasResult = CategoriasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverNombreClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverNombreCliente", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.DevolverNombreClienteRequestBody Body;
        
        public DevolverNombreClienteRequest() {
        }
        
        public DevolverNombreClienteRequest(_denissebr201224240_.websr.DevolverNombreClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverNombreClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string usuario;
        
        public DevolverNombreClienteRequestBody() {
        }
        
        public DevolverNombreClienteRequestBody(string usuario) {
            this.usuario = usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevolverNombreClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevolverNombreClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public _denissebr201224240_.websr.DevolverNombreClienteResponseBody Body;
        
        public DevolverNombreClienteResponse() {
        }
        
        public DevolverNombreClienteResponse(_denissebr201224240_.websr.DevolverNombreClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevolverNombreClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DevolverNombreClienteResult;
        
        public DevolverNombreClienteResponseBody() {
        }
        
        public DevolverNombreClienteResponseBody(string DevolverNombreClienteResult) {
            this.DevolverNombreClienteResult = DevolverNombreClienteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : _denissebr201224240_.websr.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<_denissebr201224240_.websr.Service1Soap>, _denissebr201224240_.websr.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _denissebr201224240_.websr.logCResponse _denissebr201224240_.websr.Service1Soap.logC(_denissebr201224240_.websr.logCRequest request) {
            return base.Channel.logC(request);
        }
        
        public bool logC(string user, string pass) {
            _denissebr201224240_.websr.logCRequest inValue = new _denissebr201224240_.websr.logCRequest();
            inValue.Body = new _denissebr201224240_.websr.logCRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            _denissebr201224240_.websr.logCResponse retVal = ((_denissebr201224240_.websr.Service1Soap)(this)).logC(inValue);
            return retVal.Body.logCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.logCResponse> _denissebr201224240_.websr.Service1Soap.logCAsync(_denissebr201224240_.websr.logCRequest request) {
            return base.Channel.logCAsync(request);
        }
        
        public System.Threading.Tasks.Task<_denissebr201224240_.websr.logCResponse> logCAsync(string user, string pass) {
            _denissebr201224240_.websr.logCRequest inValue = new _denissebr201224240_.websr.logCRequest();
            inValue.Body = new _denissebr201224240_.websr.logCRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((_denissebr201224240_.websr.Service1Soap)(this)).logCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _denissebr201224240_.websr.logEResponse _denissebr201224240_.websr.Service1Soap.logE(_denissebr201224240_.websr.logERequest request) {
            return base.Channel.logE(request);
        }
        
        public bool logE(string user, string pass) {
            _denissebr201224240_.websr.logERequest inValue = new _denissebr201224240_.websr.logERequest();
            inValue.Body = new _denissebr201224240_.websr.logERequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            _denissebr201224240_.websr.logEResponse retVal = ((_denissebr201224240_.websr.Service1Soap)(this)).logE(inValue);
            return retVal.Body.logEResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.logEResponse> _denissebr201224240_.websr.Service1Soap.logEAsync(_denissebr201224240_.websr.logERequest request) {
            return base.Channel.logEAsync(request);
        }
        
        public System.Threading.Tasks.Task<_denissebr201224240_.websr.logEResponse> logEAsync(string user, string pass) {
            _denissebr201224240_.websr.logERequest inValue = new _denissebr201224240_.websr.logERequest();
            inValue.Body = new _denissebr201224240_.websr.logERequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((_denissebr201224240_.websr.Service1Soap)(this)).logEAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _denissebr201224240_.websr.logDResponse _denissebr201224240_.websr.Service1Soap.logD(_denissebr201224240_.websr.logDRequest request) {
            return base.Channel.logD(request);
        }
        
        public bool logD(string user, string pass) {
            _denissebr201224240_.websr.logDRequest inValue = new _denissebr201224240_.websr.logDRequest();
            inValue.Body = new _denissebr201224240_.websr.logDRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            _denissebr201224240_.websr.logDResponse retVal = ((_denissebr201224240_.websr.Service1Soap)(this)).logD(inValue);
            return retVal.Body.logDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.logDResponse> _denissebr201224240_.websr.Service1Soap.logDAsync(_denissebr201224240_.websr.logDRequest request) {
            return base.Channel.logDAsync(request);
        }
        
        public System.Threading.Tasks.Task<_denissebr201224240_.websr.logDResponse> logDAsync(string user, string pass) {
            _denissebr201224240_.websr.logDRequest inValue = new _denissebr201224240_.websr.logDRequest();
            inValue.Body = new _denissebr201224240_.websr.logDRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((_denissebr201224240_.websr.Service1Soap)(this)).logDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _denissebr201224240_.websr.logAResponse _denissebr201224240_.websr.Service1Soap.logA(_denissebr201224240_.websr.logARequest request) {
            return base.Channel.logA(request);
        }
        
        public bool logA(string user, string pass) {
            _denissebr201224240_.websr.logARequest inValue = new _denissebr201224240_.websr.logARequest();
            inValue.Body = new _denissebr201224240_.websr.logARequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            _denissebr201224240_.websr.logAResponse retVal = ((_denissebr201224240_.websr.Service1Soap)(this)).logA(inValue);
            return retVal.Body.logAResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.logAResponse> _denissebr201224240_.websr.Service1Soap.logAAsync(_denissebr201224240_.websr.logARequest request) {
            return base.Channel.logAAsync(request);
        }
        
        public System.Threading.Tasks.Task<_denissebr201224240_.websr.logAResponse> logAAsync(string user, string pass) {
            _denissebr201224240_.websr.logARequest inValue = new _denissebr201224240_.websr.logARequest();
            inValue.Body = new _denissebr201224240_.websr.logARequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((_denissebr201224240_.websr.Service1Soap)(this)).logAAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _denissebr201224240_.websr.despedirResponse _denissebr201224240_.websr.Service1Soap.despedir(_denissebr201224240_.websr.despedirRequest request) {
            return base.Channel.despedir(request);
        }
        
        public void despedir(string id) {
            _denissebr201224240_.websr.despedirRequest inValue = new _denissebr201224240_.websr.despedirRequest();
            inValue.Body = new _denissebr201224240_.websr.despedirRequestBody();
            inValue.Body.id = id;
            _denissebr201224240_.websr.despedirResponse retVal = ((_denissebr201224240_.websr.Service1Soap)(this)).despedir(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.despedirResponse> _denissebr201224240_.websr.Service1Soap.despedirAsync(_denissebr201224240_.websr.despedirRequest request) {
            return base.Channel.despedirAsync(request);
        }
        
        public System.Threading.Tasks.Task<_denissebr201224240_.websr.despedirResponse> despedirAsync(string id) {
            _denissebr201224240_.websr.despedirRequest inValue = new _denissebr201224240_.websr.despedirRequest();
            inValue.Body = new _denissebr201224240_.websr.despedirRequestBody();
            inValue.Body.id = id;
            return ((_denissebr201224240_.websr.Service1Soap)(this)).despedirAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _denissebr201224240_.websr.cargarEmpleadoResponse _denissebr201224240_.websr.Service1Soap.cargarEmpleado(_denissebr201224240_.websr.cargarEmpleadoRequest request) {
            return base.Channel.cargarEmpleado(request);
        }
        
        public void cargarEmpleado(string direccion) {
            _denissebr201224240_.websr.cargarEmpleadoRequest inValue = new _denissebr201224240_.websr.cargarEmpleadoRequest();
            inValue.Body = new _denissebr201224240_.websr.cargarEmpleadoRequestBody();
            inValue.Body.direccion = direccion;
            _denissebr201224240_.websr.cargarEmpleadoResponse retVal = ((_denissebr201224240_.websr.Service1Soap)(this)).cargarEmpleado(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.cargarEmpleadoResponse> _denissebr201224240_.websr.Service1Soap.cargarEmpleadoAsync(_denissebr201224240_.websr.cargarEmpleadoRequest request) {
            return base.Channel.cargarEmpleadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<_denissebr201224240_.websr.cargarEmpleadoResponse> cargarEmpleadoAsync(string direccion) {
            _denissebr201224240_.websr.cargarEmpleadoRequest inValue = new _denissebr201224240_.websr.cargarEmpleadoRequest();
            inValue.Body = new _denissebr201224240_.websr.cargarEmpleadoRequestBody();
            inValue.Body.direccion = direccion;
            return ((_denissebr201224240_.websr.Service1Soap)(this)).cargarEmpleadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _denissebr201224240_.websr.cargarCategoriaResponse _denissebr201224240_.websr.Service1Soap.cargarCategoria(_denissebr201224240_.websr.cargarCategoriaRequest request) {
            return base.Channel.cargarCategoria(request);
        }
        
        public void cargarCategoria(string direccion) {
            _denissebr201224240_.websr.cargarCategoriaRequest inValue = new _denissebr201224240_.websr.cargarCategoriaRequest();
            inValue.Body = new _denissebr201224240_.websr.cargarCategoriaRequestBody();
            inValue.Body.direccion = direccion;
            _denissebr201224240_.websr.cargarCategoriaResponse retVal = ((_denissebr201224240_.websr.Service1Soap)(this)).cargarCategoria(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.cargarCategoriaResponse> _denissebr201224240_.websr.Service1Soap.cargarCategoriaAsync(_denissebr201224240_.websr.cargarCategoriaRequest request) {
            return base.Channel.cargarCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<_denissebr201224240_.websr.cargarCategoriaResponse> cargarCategoriaAsync(string direccion) {
            _denissebr201224240_.websr.cargarCategoriaRequest inValue = new _denissebr201224240_.websr.cargarCategoriaRequest();
            inValue.Body = new _denissebr201224240_.websr.cargarCategoriaRequestBody();
            inValue.Body.direccion = direccion;
            return ((_denissebr201224240_.websr.Service1Soap)(this)).cargarCategoriaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _denissebr201224240_.websr.sucursalResponse _denissebr201224240_.websr.Service1Soap.sucursal(_denissebr201224240_.websr.sucursalRequest request) {
            return base.Channel.sucursal(request);
        }
        
        public _denissebr201224240_.websr.ArrayOfString sucursal() {
            _denissebr201224240_.websr.sucursalRequest inValue = new _denissebr201224240_.websr.sucursalRequest();
            inValue.Body = new _denissebr201224240_.websr.sucursalRequestBody();
            _denissebr201224240_.websr.sucursalResponse retVal = ((_denissebr201224240_.websr.Service1Soap)(this)).sucursal(inValue);
            return retVal.Body.sucursalResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.sucursalResponse> _denissebr201224240_.websr.Service1Soap.sucursalAsync(_denissebr201224240_.websr.sucursalRequest request) {
            return base.Channel.sucursalAsync(request);
        }
        
        public System.Threading.Tasks.Task<_denissebr201224240_.websr.sucursalResponse> sucursalAsync() {
            _denissebr201224240_.websr.sucursalRequest inValue = new _denissebr201224240_.websr.sucursalRequest();
            inValue.Body = new _denissebr201224240_.websr.sucursalRequestBody();
            return ((_denissebr201224240_.websr.Service1Soap)(this)).sucursalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _denissebr201224240_.websr.registrarResponse _denissebr201224240_.websr.Service1Soap.registrar(_denissebr201224240_.websr.registrarRequest request) {
            return base.Channel.registrar(request);
        }
        
        public void registrar(int dpi, string nombre, string apellido, int nit, int telefono, string direccion, long tarjeta, int sucursal, string usuario, string contra, int estado) {
            _denissebr201224240_.websr.registrarRequest inValue = new _denissebr201224240_.websr.registrarRequest();
            inValue.Body = new _denissebr201224240_.websr.registrarRequestBody();
            inValue.Body.dpi = dpi;
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.nit = nit;
            inValue.Body.telefono = telefono;
            inValue.Body.direccion = direccion;
            inValue.Body.tarjeta = tarjeta;
            inValue.Body.sucursal = sucursal;
            inValue.Body.usuario = usuario;
            inValue.Body.contra = contra;
            inValue.Body.estado = estado;
            _denissebr201224240_.websr.registrarResponse retVal = ((_denissebr201224240_.websr.Service1Soap)(this)).registrar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.registrarResponse> _denissebr201224240_.websr.Service1Soap.registrarAsync(_denissebr201224240_.websr.registrarRequest request) {
            return base.Channel.registrarAsync(request);
        }
        
        public System.Threading.Tasks.Task<_denissebr201224240_.websr.registrarResponse> registrarAsync(int dpi, string nombre, string apellido, int nit, int telefono, string direccion, long tarjeta, int sucursal, string usuario, string contra, int estado) {
            _denissebr201224240_.websr.registrarRequest inValue = new _denissebr201224240_.websr.registrarRequest();
            inValue.Body = new _denissebr201224240_.websr.registrarRequestBody();
            inValue.Body.dpi = dpi;
            inValue.Body.nombre = nombre;
            inValue.Body.apellido = apellido;
            inValue.Body.nit = nit;
            inValue.Body.telefono = telefono;
            inValue.Body.direccion = direccion;
            inValue.Body.tarjeta = tarjeta;
            inValue.Body.sucursal = sucursal;
            inValue.Body.usuario = usuario;
            inValue.Body.contra = contra;
            inValue.Body.estado = estado;
            return ((_denissebr201224240_.websr.Service1Soap)(this)).registrarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _denissebr201224240_.websr.cotizarResponse _denissebr201224240_.websr.Service1Soap.cotizar(_denissebr201224240_.websr.cotizarRequest request) {
            return base.Channel.cotizar(request);
        }
        
        public string cotizar(float precio, float peso) {
            _denissebr201224240_.websr.cotizarRequest inValue = new _denissebr201224240_.websr.cotizarRequest();
            inValue.Body = new _denissebr201224240_.websr.cotizarRequestBody();
            inValue.Body.precio = precio;
            inValue.Body.peso = peso;
            _denissebr201224240_.websr.cotizarResponse retVal = ((_denissebr201224240_.websr.Service1Soap)(this)).cotizar(inValue);
            return retVal.Body.cotizarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.cotizarResponse> _denissebr201224240_.websr.Service1Soap.cotizarAsync(_denissebr201224240_.websr.cotizarRequest request) {
            return base.Channel.cotizarAsync(request);
        }
        
        public System.Threading.Tasks.Task<_denissebr201224240_.websr.cotizarResponse> cotizarAsync(float precio, float peso) {
            _denissebr201224240_.websr.cotizarRequest inValue = new _denissebr201224240_.websr.cotizarRequest();
            inValue.Body = new _denissebr201224240_.websr.cotizarRequestBody();
            inValue.Body.precio = precio;
            inValue.Body.peso = peso;
            return ((_denissebr201224240_.websr.Service1Soap)(this)).cotizarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _denissebr201224240_.websr.CategoriasResponse _denissebr201224240_.websr.Service1Soap.Categorias(_denissebr201224240_.websr.CategoriasRequest request) {
            return base.Channel.Categorias(request);
        }
        
        public _denissebr201224240_.websr.ArrayOfString Categorias() {
            _denissebr201224240_.websr.CategoriasRequest inValue = new _denissebr201224240_.websr.CategoriasRequest();
            inValue.Body = new _denissebr201224240_.websr.CategoriasRequestBody();
            _denissebr201224240_.websr.CategoriasResponse retVal = ((_denissebr201224240_.websr.Service1Soap)(this)).Categorias(inValue);
            return retVal.Body.CategoriasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.CategoriasResponse> _denissebr201224240_.websr.Service1Soap.CategoriasAsync(_denissebr201224240_.websr.CategoriasRequest request) {
            return base.Channel.CategoriasAsync(request);
        }
        
        public System.Threading.Tasks.Task<_denissebr201224240_.websr.CategoriasResponse> CategoriasAsync() {
            _denissebr201224240_.websr.CategoriasRequest inValue = new _denissebr201224240_.websr.CategoriasRequest();
            inValue.Body = new _denissebr201224240_.websr.CategoriasRequestBody();
            return ((_denissebr201224240_.websr.Service1Soap)(this)).CategoriasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        _denissebr201224240_.websr.DevolverNombreClienteResponse _denissebr201224240_.websr.Service1Soap.DevolverNombreCliente(_denissebr201224240_.websr.DevolverNombreClienteRequest request) {
            return base.Channel.DevolverNombreCliente(request);
        }
        
        public string DevolverNombreCliente(string usuario) {
            _denissebr201224240_.websr.DevolverNombreClienteRequest inValue = new _denissebr201224240_.websr.DevolverNombreClienteRequest();
            inValue.Body = new _denissebr201224240_.websr.DevolverNombreClienteRequestBody();
            inValue.Body.usuario = usuario;
            _denissebr201224240_.websr.DevolverNombreClienteResponse retVal = ((_denissebr201224240_.websr.Service1Soap)(this)).DevolverNombreCliente(inValue);
            return retVal.Body.DevolverNombreClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<_denissebr201224240_.websr.DevolverNombreClienteResponse> _denissebr201224240_.websr.Service1Soap.DevolverNombreClienteAsync(_denissebr201224240_.websr.DevolverNombreClienteRequest request) {
            return base.Channel.DevolverNombreClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<_denissebr201224240_.websr.DevolverNombreClienteResponse> DevolverNombreClienteAsync(string usuario) {
            _denissebr201224240_.websr.DevolverNombreClienteRequest inValue = new _denissebr201224240_.websr.DevolverNombreClienteRequest();
            inValue.Body = new _denissebr201224240_.websr.DevolverNombreClienteRequestBody();
            inValue.Body.usuario = usuario;
            return ((_denissebr201224240_.websr.Service1Soap)(this)).DevolverNombreClienteAsync(inValue);
        }
    }
}
