create database Fase3V1

use Fase3V1

CREATE TABLE Sede(
IdSede INT IDENTITY(1,1) PRIMARY KEY,
Pais VARCHAR(MAX) NOT NULL,
Comision FLOAT NOT NULL,
)
CREATE TABLE Sucursal(
IdSucursal INT IDENTITY(1,1) PRIMARY KEY,
Nombre VARCHAR(MAX) NOT NULL,
Direccion VARCHAR(MAX) NOT NULL,
Telefono INT NOT NULL,
CantidadEmpleados INT NOT NULL,
IdSede INT NOT NULL,
FOREIGN KEY (IdSede) REFERENCES Sede(IdSede)
)
CREATE TABLE Departamento(
IdDepartamento INT IDENTITY(1,1) PRIMARY KEY,
Nombre VARCHAR(MAX)   NOT NULL,
Descripcion VARCHAR(MAX),
)
CREATE TABLE AsignacionSD(
idAsignacion INT IDENTITY(1,1) PRIMARY KEY,
IdDepartamento INT NOT NULL,
IdSucursal INT NOT NULL,
FOREIGN KEY (IdDepartamento) REFERENCES Departamento(IdDepartamento),
FOREIGN KEY (IdSucursal) REFERENCES Sucursal(IdSucursal)
)
CREATE TABLE Empleado(
IdEmpleado INT IDENTITY(1,1) PRIMARY KEY,
Nombre VARCHAR(MAX) NOT NULL,
Apellido VARCHAR(MAX) NOT NULL,
Telefono INT,
Sueldo FLOAT NOT NULL,
Direccion VARCHAR(MAX),
Tipo VARCHAR(MAX) NOT NULL,
Rol INT NOT NULL,
UsuarioEmpleado VARCHAR(MAX),
PasswordE VARCHAR(MAX),
Habilitado BIT NOT NULL,
IdSucursal  INT  NOT NULL,
FOREIGN KEY (Rol) REFERENCES Departamento(IdDepartamento),
FOREIGN KEY (IdSucursal) REFERENCES Sucursal(IdSucursal)
)
CREATE TABLE Cliente(
Nombre VARCHAR(MAX) NOT NULL,
Apellido VARCHAR(MAX) NOT NULL,
Dpi BIGINT PRIMARY KEY,
Telefono INT,
Nit INT,
Direccion VARCHAR(MAX) NOT NULL,
casilla  INT IDENTITY(1,1)   NOT NULL,
Estado BIT NOT NULL,
UsuarioCliente VARCHAR(MAX)   NOT NULL,
PasswordC VARCHAR(MAX) NOT NULL,
IdSucursal INT NOT NULL,
NoTarjeta BIGINT NOT NULL,
FOREIGN KEY (IdSucursal) REFERENCES Sucursal(IdSucursal)
)
CREATE TABLE Categoria(
IdCategoria INT IDENTITY(1,1) PRIMARY KEY,
Nombre VARCHAR(MAX) NOT NULL,
Impuesto FLOAT NOT NULL
)
CREATE TABLE Lote(
IdLote INT IDENTITY(1,1) PRIMARY KEY,
FechaSalida DATE NOT NULL,
IdSucursal INT NOT NULL,
FOREIGN KEY (IdSucursal) REFERENCES Sucursal(IdSucursal)
)
CREATE TABLE Factura(
IdFactura INT IDENTITY(1,1) PRIMARY KEY,
FechaEmision DATE NOT NULL,
Dpi BIGINT NOT NULL,
FOREIGN KEY (Dpi) REFERENCES Cliente(Dpi),
)
CREATE TABLE estadoPrecio(
IdEstado INT IDENTITY(1,1) PRIMARY KEY,
Nombre VARCHAR(MAX) NOT NULL
)
CREATE TABLE Paquete(
IdPaquete INT IDENTITY(1,1) PRIMARY KEY,
Nombre VARCHAR(MAX) NOT NULL,
Descripcion VARCHAR(MAX),
peso FLOAT NOT NULL,
PrecioF VARCHAR(MAX),
Precio float,
Dpi BIGINT NOT NULL,
IdCategoria INT NULL,
IdLote INT NULL,
IdEstado INT NOT NULL,
IdSucursal INT NOT NULL,
FOREIGN KEY (IdEstado) REFERENCES estadoPrecio(IdEstado),
FOREIGN KEY (Dpi) REFERENCES Cliente(Dpi),
FOREIGN KEY (IdCategoria) REFERENCES Categoria(IdCategoria),
FOREIGN KEY (IdLote) REFERENCES Lote(IdLote),
FOREIGN KEY (IdSucursal) REFERENCES Sucursal(IdSucursal)
)
CREATE TABLE Detalle(
IdDetalle INT IDENTITY(1,1) PRIMARY KEY,
Descripcion VARCHAR(MAX) NOT NULL,
Total INT NOT NULL,
IdFactura INT NOT NULL,
IdPaquete INT NOT NULL,
FOREIGN KEY (IdPaquete) REFERENCES Paquete(IdPaquete),
FOREIGN KEY (IdFactura) REFERENCES Factura(IdFactura),
)
CREATE TABLE EstadoPaqete(
EstadoTrack INT IDENTITY(1,1) PRIMARY KEY,
estadoDes VARCHAR(MAX) NOT NULL
)
CREATE TABLE historialPa(
IdHistorialPa INT IDENTITY(1,1) PRIMARY KEY,
FechaMod VARCHAR(MAX) NOT NULL,
IdEmpleado INT NOT NULL,
IdPaquete INT NOT NULL,
EstadoTrack INT NOT NULL,
FOREIGN KEY (IdPaquete) REFERENCES Paquete(IdPaquete),
FOREIGN KEY (IdEmpleado) REFERENCES Empleado(IdEmpleado),
FOREIGN KEY (EstadoTrack) REFERENCES EstadoPaqete(EstadoTrack)
)
CREATE TABLE historialEmp(
IdHistorialE INT IDENTITY(1,1) PRIMARY KEY,
FechaInicio VARCHAR(MAX) NOT NULL,
FechaFin VARCHAR(MAX) NULL,
IdEmpleado INT NOT NULL,
Nombre VARCHAR(MAX) NOT NULL,
Apellido VARCHAR(MAX) NOT NULL,
Telefono INT,
Sueldo FLOAT NOT NULL,
Direccion VARCHAR(MAX),
Tipo VARCHAR(MAX) NOT NULL,
Rol INT NOT NULL,
UsuarioEmpleado VARCHAR(MAX),
PasswordE VARCHAR(MAX),
Habilitado BIT NOT NULL,
IdSucursal  INT  NOT NULL,
FOREIGN KEY (IdEmpleado) REFERENCES Empleado(IdEmpleado),
)
